name: parse_sdk
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter_riverpod: ^1.0.0
  freezed_annotation: ^1.0.0
  http: ^0.13.4
  json_annotation: ^4.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  freezed: ^1.0.0
  json_serializable: ^6.0.1
  build_runner: ^2.1.5
